<?php

namespace AppBundle\Repository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends \Doctrine\ORM\EntityRepository {

    /**
     * 
     * @param \AppBundle\Entity\Student $s
     */
    public function findModulesWithoutStudent(\AppBundle\Entity\Student $s) {
        $subQueryBuilder = $this->getEntityManager()->createQueryBuilder();

        $subQuery = $subQueryBuilder
                ->select(['m.id'])
                ->from(\AppBundle\Entity\Module::class, 'm')
                ->leftJoin('m.students', 's')
                ->where('s.id = :sId');

        $queryBuilder = $this->getEntityManager()->createQueryBuilder();
        return $queryBuilder->select('md')
                        ->from(\AppBundle\Entity\Module::class, 'md')
                        ->where($queryBuilder->expr()->notIn('md.id', $subQuery->getDQL()))
                        ->setParameter('sId', $s->getId())
                        ->getQuery()
                        ->getResult();
    }

}
