app:
    resource: '@AppBundle/Controller/'
    type: annotation
logout:
    path: /logout
notif-template:
    path: /notifTemplate
    defaults:
        _controller:  FrameworkBundle:Template:template
        template:     'notif-template.html.twig'