# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [teacher_provider, student_provider]           
                                
        teacher_provider:
            entity:
                class: AppBundle:Teacher
                property: login
        student_provider:
            entity:
                class: AppBundle:Student
                property: login
        
        

    role_hierarchy:
        ROLE_STUDENT: ROLE_USER
        ROLE_TEACHER: ROLE_USER
        ROLE_ADMIN: [ROLE_TEACHER, ROLE_STUDENT]
        
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/createUser, roles: ROLE_TEACHER }
        - { path: ^/studentList, roles: ROLE_TEACHER }
        - { path: ^/userList, roles: ROLE_ADMIN}
        - { path: ^/deleteModule, roles: ROLE_TEACHER }
        - { path: ^/editStudent, roles: ROLE_TEACHER }
        - { path: ^/, role: ROLE_USER }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            pattern: ^/
            anonymous: true
            logout:
                path: /logout
                target: /login
            form_login:
                login_path: login
                check_path: login
                default_target_path: lobby
                always_use_default_target_path: true
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
