<?php

namespace AppBundle\Repository\Survey;

/**
 * AssignmentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssignmentsRepository extends \Doctrine\ORM\EntityRepository
{
}
