<?php

namespace AppBundle\Repository\Survey;

/**
 * CourseObjectivesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseObjectivesRepository extends \Doctrine\ORM\EntityRepository
{
}
