<?php

namespace AppBundle\Repository\Survey;

/**
 * ExpectationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpectationsRepository extends \Doctrine\ORM\EntityRepository
{
}
