<?php

namespace AppBundle\Repository\Survey;

/**
 * IncreasedInterestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncreasedInterestRepository extends \Doctrine\ORM\EntityRepository
{
}
