<?php

namespace AppBundle\Repository\Survey;

/**
 * LastWordsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LastWordsRepository extends \Doctrine\ORM\EntityRepository
{
}
