<?php

namespace AppBundle\Repository\Survey;

/**
 * OverallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OverallRepository extends \Doctrine\ORM\EntityRepository
{
}
