<?php

namespace AppBundle\Repository\Survey;

/**
 * TeacherOverallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeacherOverallRepository extends \Doctrine\ORM\EntityRepository
{
}
