<?php

namespace AppBundle\Repository\Survey;

/**
 * TeacherKnowledgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeacherKnowledgeRepository extends \Doctrine\ORM\EntityRepository
{
}
