<?php

namespace AppBundle\Repository\Survey;

/**
 * TeacherEncouragedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeacherEncouragedRepository extends \Doctrine\ORM\EntityRepository
{
}
