<?php

namespace AppBundle\Repository\Survey;

/**
 * TeacherGenuineConcernRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeacherGenuineConcernRepository extends \Doctrine\ORM\EntityRepository
{
}
