<?php

namespace AppBundle\Repository\Survey;

/**
 * TeacherEffectiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeacherEffectiveRepository extends \Doctrine\ORM\EntityRepository
{
}
