<?php

namespace AppBundle\Repository\Survey;

/**
 * TeacherEnthusiasmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeacherEnthusiasmRepository extends \Doctrine\ORM\EntityRepository
{
}
