<?php

namespace AppBundle\Repository\Survey;

/**
 * TextBooksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextBooksRepository extends \Doctrine\ORM\EntityRepository
{
}
