<?php

namespace AppBundle\Repository\Survey;

/**
 * WouldRecommendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WouldRecommendRepository extends \Doctrine\ORM\EntityRepository
{
}
